version: '3.4'

services:
  postgres:
    ports:
      - "5432:5432"
    # volumes:
      # - ./_volume_database:/var/lib/postgresql/data/ # doesn't work because of ownership
  nginx:
    image: olivierdalang/spcgeonode:nginx-dev
    volumes:
      - ./_volume_static:/spcgeonode-static/
      - ./_volume_media:/spcgeonode-media/
      - ./_volume_certbot:/spcgeonode-certbot/
  django:
    image: olivierdalang/spcgeonode:django-dev
    environment:
      - "DEBUG=True"
    volumes:
      - './django:/spcgeonode/'
      - ./_volume_static:/spcgeonode-static/
      - ./_volume_media:/spcgeonode-media/
    command: ["uwsgi", "--chdir=/spcgeonode", "--module=spcgeonode.wsgi", "--env=DJANGO_SETTINGS_MODULE=spcgeonode.settings", "--socket=:8000", "--py-autoreload=2"]
  celery:
    image: olivierdalang/spcgeonode:django-dev
    volumes:
      - './django:/spcgeonode/'
  celerycam:
    image: olivierdalang/spcgeonode:django-dev
    volumes:
      - './django:/spcgeonode/'

  geoserver:
    image: olivierdalang/spcgeonode:geoserver-dev
    volumes:
      - ./_volume_geodatadir:/spcgeonode-geodatadir/

  letsencrypt:
    image: olivierdalang/spcgeonode:letsencrypt-dev
    volumes:
      - ./_volume_certbot:/spcgeonode-certbot/

  pgdumper:
    image: olivierdalang/spcgeonode:pgdumper-dev
    build: ./pgdumper/
    volumes:
      - ./_volume_pgdumps:/spcgeonode-pgdumps/

  syncthing:
    image: olivierdalang/spcgeonode:syncthing-dev
    volumes:
      - ./_volume_pgdumps:/spcgeonode-pgdumps/
      - ./_volume_media:/spcgeonode-media/
      - ./_volume_geodatadir:/spcgeonode-geodatadir/

secrets:
  admin_username:
    file: _devsecrets/admin_username
    external: false
  admin_password:
    file: _devsecrets/admin_password
    external: false