version: '3'

services:
  postgres:
    ports:
      - "5432:5432"
    # volumes:
      # - ./volumes/database:/var/lib/postgresql/data # doesn't work because of ownership
  nginx:
    # command: [nginx-debug, '-g', 'daemon off;']
    volumes:
      - ./volumes/static:/spcnode-static
      - ./volumes/media:/spcnode-media
  django:
    environment:
      - "DEBUG=True"
    volumes:
      - './django:/spcnode'
      - ./volumes/static:/spcnode-static
      - ./volumes/media:/spcnode-media
      - 'C:\Users\Olivier\Dropbox\Affaires\SPC\Sources\geonode-offlineosm:/offlineosm' # TODO : remove this (once geonode-offlineosm is in pypi)
    command: ["uwsgi", "--chdir=/spcnode", "--module=spcnode.wsgi", "--env=DJANGO_SETTINGS_MODULE=spcnode.settings", "--socket=:8000", "--py-autoreload=2"]
  celery:
    volumes:
      - './django:/spcnode'
      - ./volumes/static:/spcnode-static
      - ./volumes/media:/spcnode-media      
      - 'C:\Users\Olivier\Dropbox\Affaires\SPC\Sources\geonode-offlineosm:/offlineosm' # TODO : remove this (once geonode-offlineosm is in pypi)
  geoserver:
    volumes:
      - ./volumes/geodatadir:/spcnode-geodatadir/
  # backuper:
  #   volumes:
  #     # - ./volumes/database:/tobackup/spcnode-database # doesn't work because of ownership
  #     - ./volumes/media:/tobackup/spcnode-media
  #     - ./volumes/geodatadir:/tobackup/spcnode-geodatadir
